#!/usr/bin/env python3
"""Refresh this public mirror from the private quote bank.

Reads the private ledger and author table and writes the public data files
with the private bank's tools/bank.py functions (validation, CSV form, reading
view, JSON, Data Package).

Left out:
    entries whose category is in PRIVATE_CATEGORIES
    entries by an author of any PRIVATE_CATEGORIES entry
    entries whose id is in PRIVATE_IDS
    author rows whose entries are all left out (a kept alias keeps its bio row)
    the source_files column

Stops without writing if a kept entry's notes name a left-out id, or if a kept
field contains the name of a PRIVATE_CATEGORIES author.

Reads:  <bank>/quotes.csv, <bank>/authors.csv, <bank>/tools/bank.py;
        this repository's git history (creation dates)
Writes: quotes.csv, authors.csv, QUOTES.md, quotes.json, datapackage.json
        (repository root)

Usage:
    python3 tools/mirror.py <path to the private bank>

File: tools/mirror.py, Python 3, created 2026-09-29.
"""
import csv
import importlib.util
import json
import os
import sys

PRIVATE_CATEGORIES = {"Own Writing"}
PRIVATE_IDS = {
    "Q0250",  # no author found
    "Q0531",  # speaker unidentified
    "Q0639",  # private person
}
DROPPED_COLUMN = "source_files"

HERE = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))


def load_bank(src):
    """The private bank's tools/bank.py, imported from its file."""
    spec = importlib.util.spec_from_file_location(
        "bank", os.path.join(src, "tools", "bank.py"))
    bank = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(bank)
    return bank


def read(path):
    with open(path, newline="", encoding="utf-8") as f:
        return list(csv.DictReader(f))


def own_authors(quotes):
    """Authors of PRIVATE_CATEGORIES entries in the private ledger."""
    return {q["author"] for q in quotes
            if q["category"] in PRIVATE_CATEGORIES and q["author"]}


def private(q, own):
    return (q["id"] in PRIVATE_IDS or q["author"] in own
            or q["category"] in PRIVATE_CATEGORIES)


def main(src):
    bank = load_bank(src)
    quotes = read(os.path.join(src, "quotes.csv"))
    authors = read(os.path.join(src, "authors.csv"))

    own = own_authors(quotes)
    dropped = {q["id"] for q in quotes if private(q, own)}
    kept = [q for q in quotes if not private(q, own)]
    names = {q["author"] for q in kept}
    aliased = {a["alias_of"] for a in authors
               if a["name"] in names and a["status"] == "alias"}
    people = [a for a in authors if a["name"] in names or a["name"] in aliased]

    errors = bank.validate(kept)
    for q in kept:
        errors += [f"{q['id']} refers to private {i}; resolve by hand"
                   for i in dropped if i in q["notes"]]
    for row in kept + people:
        public = {k: v for k, v in row.items() if k != DROPPED_COLUMN}
        errors += [f"{row.get('id') or row['name']} mentions {name}"
                   for name in own
                   if any(name in value for value in public.values())]
    if errors:
        sys.exit("\n".join(errors))

    columns = [c for c in bank.COLUMNS if c != DROPPED_COLUMN]
    public_rows = [{c: q[c] for c in columns} for q in kept]
    path = lambda name: os.path.join(HERE, name)  # noqa: E731
    created = lambda name, full=False: bank.first_commit(  # noqa: E731
        path(name), root=HERE, full=full)

    bank.write_csv(path("quotes.csv"), columns, public_rows)
    bank.write_csv(path("authors.csv"), bank.AUTHOR_COLUMNS, people)

    view = bank.as_markdown(kept, made_by="tools/mirror.py",
                            path=path("QUOTES.md"), created=created("QUOTES.md"))
    with open(path("QUOTES.md"), "w", encoding="utf-8") as f:
        f.write(view)

    data = json.loads(bank.as_json(kept))
    for entry in data["entries"]:
        entry.pop(DROPPED_COLUMN, None)
    with open(path("quotes.json"), "w", encoding="utf-8") as f:
        f.write(json.dumps(data, ensure_ascii=False, indent=2) + "\n")

    made = "Generated by tools/mirror.py from the private bank."
    descriptor = bank.package(
        "quotebank", "quotebank",
        "Quotations, poems, prose passages, proverbs and lyrics by public "
        "figures: the public part of a private quote bank. " + made,
        created("quotes.csv", full=True),
        [bank.csv_resource(
            "quotes", "quotes.csv",
            "One row per entry, sorted by id.", created("quotes.csv"),
            bank.table_schema(bank.QUOTE_FIELDS, drop=(DROPPED_COLUMN,),
                              primary_key="id", foreign_keys=[bank.AUTHOR_KEY])),
         bank.csv_resource(
            "authors", "authors.csv",
            "One row per author name used in quotes.csv, sorted by name "
            "(case-insensitive).", created("authors.csv"),
            bank.table_schema(bank.AUTHOR_FIELDS, primary_key="name",
                              foreign_keys=[bank.ALIAS_KEY])),
         bank.json_resource(
            "quotes-json", "quotes.json",
            'quotes.csv as JSON: {"count": N, "entries": [...]}, one object '
            "per row with the same fields; tags is a list.",
            created("quotes.json"))])
    with open(path("datapackage.json"), "w", encoding="utf-8") as f:
        f.write(descriptor)

    print(f"{len(kept)} entries, {len(people)} author rows; "
          f"left out {', '.join(sorted(dropped))}")


if __name__ == "__main__":
    if len(sys.argv) != 2:
        sys.exit(__doc__)
    main(os.path.abspath(os.path.expanduser(sys.argv[1])))
